### ISSUE TITLE
What is the purpose of this library?

### ISSUE THREAD

**Issue by slidenerd** [SoftwareBrothers/adminjs-passwords#10]
I am sorry if this sounds like a stupid question but I honestly did not find anything on the npmjs package or anywhere except the documentation [where it shows how to use features](https://docs.adminjs.co/tutorials/using-adminjs-features)

I have a ResetToken model that has 3 fields, **account_id, token_expiry_date and the token** itself
I hash the tokens using argon2 and store it in the database
My sequelize model already has a beforeUpdate and beforeCreate hook that performs the hashing

```
  @BeforeUpdate
  @BeforeCreate
  static async makeUpperCase(instance: ResetToken) {
    instance.token = await generateHash(instance.token);
  }
```
**CREATING**

<img width="658" alt="Screenshot 2022-10-11 at 6 26 14 PM" src="https://user-images.githubusercontent.com/5139030/195096689-bccbeded-62af-4f85-a8bd-1d45d7f1cc4f.png">

When creating a new entry, all I have to do is input the raw token and it immediately stores it in its hash form

**VIEWING**
<img width="801" alt="Screenshot 2022-10-11 at 6 26 58 PM" src="https://user-images.githubusercontent.com/5139030/195096899-1c514087-f7af-4d2c-8022-50f6ef3e052f.png">
When viewing it shows me the hashed value of the token

What does @adminjs/passwords do exactly? The data will already be hashed at the model level, no?
In that features documentation it has 2 properties, encryptedPassword and password? Is this library suppoesd to be used when you are encrypting passwords instead of hashing them to hide the plaintext passwords?

**Comment by dziraf** [comment]
This is to allow you to change the password of users if you choose to manage them in the admin panel.

> In that features documentation it has 2 properties, encryptedPassword and password
These are used to map values. `password` is a virtual property used to store the raw value before it is hashed, `encryptedPassword` is the actual property that gets saved in the database.
