### ISSUE TITLE
4.0.0+ is not importable

### ISSUE THREAD

**Issue by synic** [SoftwareBrothers/adminjs-passwords#17]

**Comment by dziraf** [comment]
Can you be more specific? I've just checked in our example app and it works correctly.

https://github.com/SoftwareBrothers/adminjs-example-app/blob/master/src/sources/mongoose/resources/admin.resource.ts (You have to enable new/edit to test)

https://github.com/SoftwareBrothers/adminjs-passwords/assets/16668924/29b73ffc-9a95-48ea-a69b-e8ba30e06131

**Comment by synic** [comment]
I mean that when you type:

```ts
import passwordsFeature from '@adminjs/passwords';
```

It says that it cannot find the module `@adminjs/passwords` or it's corresponding type declarations. The same thing is happening for `@adminjs/nestjs` 6.0.1: https://github.com/SoftwareBrothers/adminjs-nestjs/issues/55

**Comment by dziraf** [comment]
This doesn't happen in our example/demo app which is also hosted on a remote environment which probably means you hadn't followed the migration guide & hadn't moved to ESM.
